[book]
authors = ["K Henry LLC"]
multilingual = false
src = "."
title = "agent"

[output.html]
git-repository-url = "https://github.com/k-henry-org/agent"
edit-url-template = "https://github.com/k-henry-org/agent/edit/main/docs/{path}"
